version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: immer
    versions:
    - 9.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: parcel-plugin-static-files-copy
    versions:
    - 2.5.1
  - dependency-name: swr
    versions:
    - 0.4.1
